CREATE TABLE IF NOT EXISTS `couples` (
	`id` INT NOT NULL,
	`player1Id` INT NOT NULL DEFAULT '0',
	`player2Id` INT NOT NULL DEFAULT '0',
	`maried` VARCHAR(5) DEFAULT NULL,
	`affiancedDate` bigint DEFAULT '0',
	`weddingDate` bigint DEFAULT '0',
	PRIMARY KEY  (`id`),
	FOREIGN KEY FK_COUPLE_CHARACTER(player1Id) REFERENCES characters(obj_Id) ON DELETE CASCADE,
	FOREIGN KEY FK_COUPLE_CHARACTER_F(player2Id) REFERENCES characters(obj_Id) ON DELETE CASCADE

);