DROP TABLE IF EXISTS `mail`;
CREATE TABLE IF NOT EXISTS `mail` (
  `id` INT NOT NULL,
  `sender` INT NOT NULL DEFAULT 0,
  `receiver` INT NOT NULL DEFAULT 0,
  `subject` TINYTEXT,
  `content` TEXT,
  `expiration` BIGINT unsigned NOT NULL DEFAULT 0,
  `fee` BIGINT NOT NULL DEFAULT 0,
  `has_attachment` BOOLEAN NOT NULL DEFAULT FALSE,
  `unread` BOOLEAN NOT NULL DEFAULT TRUE,
  `sender_deleted` BOOLEAN NOT NULL  DEFAULT FALSE,
  `receiver_deleted` BOOLEAN NOT NULL DEFAULT FALSE,
  `locked` BOOLEAN NOT NULL DEFAULT FALSE,
  `type` ENUM('REGULAR','NEWS_INFORMER','NPC','BIRTHDAY','COMMISSION_ITEM_RETURNED','COMMISSION_ITEM_SOLD','MENTOR_NPC','PRIME_SHOP_GIFT') NOT NULL DEFAULT 'REGULAR',
  `returned` BOOLEAN NOT NULL DEFAULT FALSE,
  `item` INT NOT NULL DEFAULT 0,
  `enchant` SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8MB4;

