DROP TABLE IF EXISTS `player_variables`;
CREATE TABLE IF NOT EXISTS `player_variables` (
    `player_id` INT UNSIGNED NOT NULL,
    `revenge_teleports` SMALLINT NOT NULL DEFAULT 0,
    `revenge_locations` SMALLINT NOT NULL DEFAULT 0,
    `hair_accessory_enabled` TINYINT(1) DEFAULT 1 NULL,
    `world_chat_used` INT DEFAULT 0 NULL,
	`vitality_items_used` INT DEFAULT 0 NULL,
	`ability_points_main_class_used` INT DEFAULT 0 NULL,
	`ability_points_dual_class_used` INT DEFAULT 0 NULL,
	`revelation_skill_main_class_1` INT DEFAULT 0 NULL,
	`revelation_skill_main_class_2` INT DEFAULT 0 NULL,
	`revelation_skill_dual_class_1` INT DEFAULT 0 NULL,
	`revelation_skill_dual_class_2` INT DEFAULT 0 NULL,
	`extend_drop` VARCHAR(255) NULL,
	`fortune_telling` INT DEFAULT 0 NULL,
	`fortune_telling_black_cat` TINYINT(1) DEFAULT 0 NULL,
	`hunting_zone_reset_time` VARCHAR(255) NULL,
	`autocp` INT DEFAULT 0 NULL,
	`autohp` INT DEFAULT 0 NULL,
	`automp` INT DEFAULT 0 NULL,
	`exp_off` TINYINT(1) DEFAULT 0 NULL,
	`items_rewarded` TINYINT(1) DEFAULT 0 NULL,
	`henna1_duration` BIGINT DEFAULT 0 NULL,
	`henna2_duration` BIGINT DEFAULT 0 NULL,
	`henna3_duration` BIGINT DEFAULT 0 NULL,
	`visual_hair_id` INT NULL,
	`visual_hair_color_id` INT NULL,
	`visual_face_id` INT NULL,
	`instance_origin` VARCHAR(255) NULL,
	`instance_restore` INT DEFAULT 0 NULL,
	`mentor_penalty_id` INT NULL,
	`mentor_penalty_time` BIGINT DEFAULT 0 NULL,
	`claimed_clan_rewards` INT DEFAULT 0 NULL,
	`cond_override_key` VARCHAR(255) NULL,
	`ui_key_mapping` VARCHAR(255) NULL,
	`attendance_date` BIGINT DEFAULT 0 NULL,
	`attendance_index` INT DEFAULT 0 NULL,
	`unclaimed_olympiad_points` INT DEFAULT 0 NULL,
	`monster_return` INT DEFAULT -1 NULL,
    PRIMARY KEY (`player_id`),
    FOREIGN KEY (`player_id`) REFERENCES characters(`charId`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

