/*
 * Copyright © 2019-2020 L2JOrg
 *
 * This file is part of the L2JOrg project.
 *
 * L2JOrg is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * L2JOrg is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package org.l2j.gameserver.data.database.data;

import org.l2j.commons.database.annotation.Table;
import org.l2j.gameserver.model.punishment.PunishmentAffect;
import org.l2j.gameserver.model.punishment.PunishmentType;

/**
 * @author JoeAlisson
 */
@Table(value = "punishments", autoGeneratedProperty = "id")
public class PunishmentData {

    private int id;
    private String key;
    private PunishmentAffect affect;
    private PunishmentType type;
    private long expiration;
    private String reason;
    private String punisher;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public PunishmentAffect getAffect() {
        return affect;
    }

    public void setAffect(PunishmentAffect affect) {
        this.affect = affect;
    }

    public PunishmentType getType() {
        return type;
    }

    public void setType(PunishmentType type) {
        this.type = type;
    }

    public long getExpiration() {
        return expiration;
    }

    public void setExpiration(long expiration) {
        this.expiration = expiration;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public String getPunisher() {
        return punisher;
    }

    public void setPunisher(String punisher) {
        this.punisher = punisher;
    }

    public static PunishmentData of(String key, PunishmentAffect affect, PunishmentType type, long expiration, String reason, String punisher) {
        var data = new PunishmentData();
        data.key = key;
        data.affect = affect;
        data.type = type;
        data.expiration = expiration;
        data.reason = reason;
        data.punisher = punisher;
        return data;
    }
}
