import org.l2j.scripts.ai.bosses.*;
import org.l2j.scripts.handlers.actionhandlers.*;
import org.l2j.scripts.handlers.actionshifthandlers.*;
import org.l2j.scripts.handlers.admincommandhandlers.AdminCoins;
import org.l2j.scripts.handlers.conditions.CategoryTypeCondition;
import org.l2j.scripts.handlers.conditions.NpcLevelCondition;
import org.l2j.scripts.handlers.conditions.PlayerLevelCondition;
import org.l2j.scripts.handlers.effecthandlers.*;
import org.l2j.scripts.handlers.effecthandlers.stat.*;
import org.l2j.scripts.handlers.itemhandlers.TransformationBook;
import org.l2j.scripts.handlers.skillconditionhandlers.*;
import org.l2j.scripts.quests.tutorial.darkelf.Q204_Tutorial;
import org.l2j.scripts.quests.tutorial.dwarf.Q206_Tutorial;
import org.l2j.scripts.quests.tutorial.elf.Q203_Tutorial;
import org.l2j.scripts.quests.tutorial.fighter.Q201_Tutorial;
import org.l2j.scripts.quests.tutorial.kamael.Q10960_Tutorial;
import org.l2j.scripts.quests.tutorial.mage.Q202_Tutorial;
import org.l2j.scripts.quests.tutorial.orc.Q205_Tutorial;

open module org.l2j.scripts {

    requires java.desktop;
    requires java.sql;
    requires io.github.joealisson.primitive;
    requires org.l2j.gameserver;
    requires org.slf4j;

    provides org.l2j.gameserver.model.conditions.ConditionFactory
            with NpcLevelCondition.Factory,
                CategoryTypeCondition.Factory,
                PlayerLevelCondition.Factory;

    provides org.l2j.gameserver.engine.skill.api.SkillEffectFactory
            with AbnormalShield.Factory,
                AcquireCostume.Factory,
                AcquireRandomCostume.Factory,
                AddHate.Factory,
                AddHuntingTime.Factory,
                AddTeleportBookmarkSlot.Factory,
                StatModify.Factory,
                AttackTrait.Factory,
                Backstab.Factory,
                BaseStatsModify.Factory,
                Betray.Factory,
                BlockAbnormalSlot.Factory,
                BlockAction.Factory,
                BlockActions.Factory,
                BlockChat.Factory,
                BlockControl.Factory,
                BlockEscape.Factory,
                BlockMove.Factory,
                BlockParty.Factory,
                BlockResurrection.Factory,
                BlockSkill.Factory,
                BlockTarget.Factory,
                Bluff.Factory,
                BuffBlock.Factory,
                CallParty.Factory,
                CallPc.Factory,
                CallSkill.Factory,
                CheapShot.Factory,
                ChameleonRest.Factory,
                ChangeFace.Factory,
                ChangeHairColor.Factory,
                ChangeHairStyle.Factory,
                Confuse.Factory,
                ConsumeBody.Factory,
                ConvertItem.Factory,
                Cp.Factory,
                CpHeal.Factory,
                CpHealPercent.Factory,
                StatPositionBased.Factory,
                StatHpBased.Factory,
                DamageBlock.Factory,
                DamageByAttack.Factory,
                DamOverTime.Factory,
                DeathLink.Factory,
                DebuffBlock.Factory,
                DefenceTrait.Factory,
                DeleteHate.Factory,
                DeleteHateOfMe.Factory,
                Detection.Factory,
                DisableTargeting.Factory,
                Disarm.Factory,
                DispelAll.Factory,
                DispelByCategory.Factory,
                DispelBySlot.Factory,
                DispelBySlotMyself.Factory,
                DispelBySlotProbability.Factory,
                EnergyAttack.Factory,
                EnlargeAbnormalSlot.Factory,
                EnlargeSlot.Factory,
                Escape.Factory,
                FakeDeath.Factory,
                FatalBlow.Factory,
                Fear.Factory,
                Feed.Factory,
                Flag.Factory,
                FocusMomentum.Factory,
                FocusMaxMomentum.Factory,
                FocusSouls.Factory,
                GetAgro.Factory,
                GiveClanReputation.Factory,
                GiveSp.Factory,
                GiveXp.Factory,
                GiveExpAndSp.Factory,
                Grow.Factory,
                HairAccessorySet.Factory,
                HeadquarterCreate.Factory,
                Heal.Factory,
                HealOverTime.Factory,
                HealPercent.Factory,
                HealDamOverTime.Factory,
                Hide.Factory,
                Hp.Factory,
                HpByLevel.Factory,
                HpCpHeal.Factory,
                HpDrain.Factory,
                IgnoreDeath.Factory,
                ImmobilePetBuff.Factory,
                KnockBack.Factory,
                Lethal.Factory,
                Lucky.Factory,
                MagicalAttack.Factory,
                MagicalAttackByAbnormal.Factory,
                MagicalAttackByAbnormalSlot.Factory,
                MagicalAttackMp.Factory,
                MagicalAttackRange.Factory,
                MagicalSoulAttack.Factory,
                MagicMpCost.Factory,
                ManaDamOverTime.Factory,
                ManaHeal.Factory,
                ManaHealByLevel.Factory,
                ManaHealOverTime.Factory,
                ManaHealPercent.Factory,
                ModifyMagicLampPoints.Factory,
                VitalStatModify.Factory,
                ModifyVital.Factory,
                Mp.Factory,
                MpConsumePerLevel.Factory,
                Mute.Factory,
                NoblesseBless.Factory,
                ObtainSoul.Factory,
                OpenChest.Factory,
                OpenCommonRecipeBook.Factory,
                OpenDoor.Factory,
                OpenDwarfRecipeBook.Factory,
                Passive.Factory,
                PhysicalAttack.Factory,
                PhysicalAttackHpLink.Factory,
                PhysicalAttackMute.Factory,
                PhysicalMute.Factory,
                PhysicalShieldAngleAll.Factory,
                PhysicalSoulAttack.Factory,
                PkCount.Factory,
                PolearmSingleTarget.Factory,
                ProtectionBlessing.Factory,
                PullBack.Factory,
                RandomizeHate.Factory,
                RealDamage.Factory,
                RebalanceHP.Factory,
                ReduceDamage.Factory,
                ReduceDropPenalty.Factory,
                Relax.Factory,
                ResistAbnormalByCategory.Factory,
                ResistDispelByCategory.Factory,
                Restoration.Factory,
                RestorationRandom.Factory,
                Resurrection.Factory,
                ResurrectionSpecial.Factory,
                Reuse.Factory,
                ReuseSkillById.Factory,
                Root.Factory,
                SayhaGraceSupport.Factory,
                SendSystemMessageToClan.Factory,
                ServitorShare.Factory,
                SilentMove.Factory,
                SkillCritical.Factory,
                SkillEvasion.Factory,
                SkillTurning.Factory,
                SoulBlow.Factory,
                SoulEating.Factory,
                Speed.Factory,
                Spoil.Factory,
                StatByMoveType.Factory,
                StatUp.Factory,
                StatsLinkedEffect.Factory,
                StealAbnormal.Factory,
                Stun.Factory,
                Summon.Factory,
                SummonAgathion.Factory,
                SummonCubic.Factory,
                SummonNpc.Factory,
                SummonPet.Factory,
                Sweeper.Factory,
                TakeCastle.Factory,
                TakeCastleStart.Factory,
                TalismanSlot.Factory,
                TargetCancel.Factory,
                TargetMe.Factory,
                TargetMeProbability.Factory,
                Teleport.Factory,
                TeleportToTarget.Factory,
                TransferDamageToPlayer.Factory,
                TransferHate.Factory,
                Transformation.Factory,
                TriggerSkillByAttack.Factory,
                TriggerSkillByAttacking.Factory,
                TriggerSkillByAvoid.Factory,
                TriggerSkillByChargeShot.Factory,
                TriggerSkillByDamage.Factory,
                TriggerSkillByChangeExp.Factory,
                TriggerSkillByMagicType.Factory,
                TriggerSkillBySkill.Factory,
                TwoHandedBluntBonus.Factory,
                TwoHandedSwordBonus.Factory,
                Unsummon.Factory,
                UnsummonAgathion.Factory,
                VampiricAttack.Factory,
                VipPoint.Factory
            ;

    provides org.l2j.gameserver.engine.skill.api.SkillConditionFactory
            with BuildAdvanceBaseSkillCondition.Factory,
                BuildCampSkillCondition.Factory,
                CanBookmarkAddSlotSkillCondition.Factory,
                CannotUseInTransformSkillCondition.Factory,
                CanSummonCubicSkillCondition.Factory,
                CanSummonSkillCondition.Factory,
                CanSummonPetSkillCondition.Factory,
                CanSummonSiegeGolemSkillCondition.Factory,
                CanTransformSkillCondition.Factory,
                CanUntransformSkillCondition.Factory,
                CanUseInBattlefieldSkillCondition.Factory,
                CanUseSwoopCannonSkillCondition.Factory,
                CheckLevelSkillCondition.Factory,
                CheckRangeSkillCondition.Factory,
                FemaleSkillCondition.Factory,
                ConsumeBodySkillCondition.Factory,
                EnergySavedSkillCondition.Factory,
                EquipArmorSkillCondition.Factory,
                EquipShieldSkillCondition.Factory,
                EquipWeaponSkillCondition.Factory,
                NotFearedSkillCondition.Factory,
                NotInUnderwaterSkillCondition.Factory,
                NonChaoticSkillCondition.Factory,
                OpBlinkSkillCondition.Factory,
                OpCallPcSkillCondition.Factory,
                OpCanEscapeSkillCondition.Factory,
                OpChangeWeaponSkillCondition.Factory,
                OpCheckAbnormalSkillCondition.Factory,
                OpCheckClassListSkillCondition.Factory,
                OpCheckResidenceSkillCondition.Factory,
                OpEnergyMaxSkillCondition.Factory,
                OpEncumberedSkillCondition.Factory,
                OpExistNpcSkillCondition.Factory,
                OpHaveSummonSkillCondition.Factory,
                OpHomeSkillCondition.Factory,
                OpNeedAgathionSkillCondition.Factory,
                KillerSkillCondition.Factory,
                OpPledgeSkillCondition.Factory,
                OpResurrectionSkillCondition.Factory,
                OpSkillAcquireSkillCondition.Factory,
                OpSoulMaxSkillCondition.Factory,
                OpSweeperSkillCondition.Factory,
                SkillConditionTargetFactory,
                OpUnlockSkillCondition.Factory,
                OpWyvernSkillCondition.Factory,
                PossessHolythingSkillCondition.Factory,
                RemainStatusSkillCondition.Factory,
                SoulSavedSkillCondition.Factory,
                TargetMyPledgeSkillCondition.Factory;

    provides org.l2j.gameserver.model.events.AbstractScript
        with org.l2j.scripts.instances.MonsterArena.MonsterArena,
            org.l2j.scripts.instances.ResidenceOfQueenNebula.ResidenceOfQueenNebula,
            org.l2j.scripts.instances.ResidenceOfKingProcella.ResidenceOfKingProcella,
            org.l2j.scripts.instances.ResidenceOfKingPetram.ResidenceOfKingPetram,
            org.l2j.scripts.instances.ResidenceOfKingIgnis.ResidenceOfKingIgnis,
            org.l2j.scripts.instances.GolbergRoom.GolbergRoom,
            org.l2j.scripts.instances.LastImperialTomb.LastImperialTomb,
            org.l2j.scripts.instances.sevensigns.SevenSigns,
            org.l2j.scripts.events.ChefMonkeyEvent.ChefMonkeyEvent,
            org.l2j.scripts.events.EveTheFortuneTeller.EveTheFortuneTeller,
            org.l2j.scripts.events.HappyHours.HappyHours,
            org.l2j.scripts.events.LetterCollector.LetterCollector,
            org.l2j.scripts.events.MerrySquashmas.MerrySquashmas,
            org.l2j.scripts.events.SquashEvent.SquashEvent,
            org.l2j.scripts.events.ThePowerOfLove.ThePowerOfLove,
            org.l2j.scripts.events.TotalRecall.TotalRecall,
            org.l2j.scripts.events.WatermelonNinja.WatermelonNinja,

            // custom
            org.l2j.scripts.custom.events.Elpies.Elpies,
            org.l2j.scripts.custom.events.Rabbits.Rabbits,
            org.l2j.scripts.custom.events.Race.Race,
            org.l2j.scripts.custom.events.TeamVsTeam.TvT,

            org.l2j.scripts.ai.areas.CrumaTower.SummonPc,
            org.l2j.scripts.ai.areas.DragonValley.CaveMaiden,
            org.l2j.scripts.ai.areas.DragonValley.LordIshka,
            org.l2j.scripts.ai.areas.DungeonOfAbyss.SoulTracker.Ingrit,
            org.l2j.scripts.ai.areas.DungeonOfAbyss.SoulTracker.Iris,
            org.l2j.scripts.ai.areas.DungeonOfAbyss.SoulTracker.Magrit,
            org.l2j.scripts.ai.areas.DungeonOfAbyss.SoulTracker.Rosammy,
            org.l2j.scripts.ai.areas.DungeonOfAbyss.Tores.Tores,
            org.l2j.scripts.ai.areas.DwarvenVillage.Toma.Toma,
            org.l2j.scripts.ai.areas.LairOfAntharas.Pytan,
            org.l2j.scripts.ai.areas.TalkingIsland.Roxxy,
            org.l2j.scripts.ai.areas.TowerOfInsolence.Ateld,
            org.l2j.scripts.ai.areas.PlainsOfDion,
            org.l2j.scripts.ai.areas.ImperialTomb.FourSepulchers.FourSepulchers,
            org.l2j.scripts.ai.areas.CallOfTheSpirits.CallOfTheSpirits,
            org.l2j.scripts.ai.areas.Varkas.Althars,
            org.l2j.scripts.ai.areas.Ketra.FireCamp,
            org.l2j.scripts.ai.areas.GiantCave.Scout,
            org.l2j.scripts.ai.areas.GiantCave.Batur,
            org.l2j.scripts.ai.areas.GiantCave.EntranceRoom,
            org.l2j.scripts.ai.areas.TowerOfInsolence.TowerOfInsolence,
            org.l2j.scripts.ai.areas.AligatorIsland.Nos,
            org.l2j.scripts.ai.areas.ForestOfTheMirrors.Mirrors,
            org.l2j.scripts.ai.areas.TowerOfInsolence.HeavenlyRift.Bomb,
            org.l2j.scripts.ai.areas.TowerOfInsolence.HeavenlyRift.DivineAngel,
            org.l2j.scripts.ai.areas.TowerOfInsolence.HeavenlyRift.Tower,


                Antharas,
                Baium,
                Core,
                Orfen,
                QueenAnt,
                Zaken,
            org.l2j.scripts.ai.bosses.LimitBarrier,
            org.l2j.scripts.ai.bosses.RaidZone,


            org.l2j.scripts.ai.others.ArenaManager.ArenaManager,
            org.l2j.scripts.ai.others.CastleBlacksmith.CastleBlacksmith,
            org.l2j.scripts.ai.others.CastleChamberlain.CastleChamberlain,
            org.l2j.scripts.ai.others.CastleDoorManager.CastleDoorManager,
            org.l2j.scripts.ai.others.CastleMercenaryManager.CastleMercenaryManager,
            org.l2j.scripts.ai.others.CastleSiegeManager.CastleSiegeManager,
            org.l2j.scripts.ai.others.CastleTeleporter.CastleTeleporter,
            org.l2j.scripts.ai.others.CastleWarehouse.CastleWarehouse,
            org.l2j.scripts.ai.others.ClanHallAuctioneer.ClanHallAuctioneer,
            org.l2j.scripts.ai.others.ClanHallDoorManager.ClanHallDoorManager,
            org.l2j.scripts.ai.others.ClanHallManager.ClanHallManager,
            org.l2j.scripts.ai.others.ClassMaster.ClassMaster,
            org.l2j.scripts.ai.others.DimensionalMerchant.DimensionalMerchant,
            org.l2j.scripts.ai.others.MonumentOfHeroes.MonumentOfHeroes,
            org.l2j.scripts.ai.others.OlyManager.OlympiadManager,
            org.l2j.scripts.ai.others.guide.NewbieGuide,
            org.l2j.scripts.ai.others.OlyBuffer.OlyBuffer,
            org.l2j.scripts.ai.others.Proclaimer.Proclaimer,
            org.l2j.scripts.ai.others.Servitors.SinEater,
            org.l2j.scripts.ai.others.Servitors.TreeOfLife,
            org.l2j.scripts.ai.others.Spawns.EilhalderVonHellmann,
            org.l2j.scripts.ai.others.Spawns.DayNightSpawns,
            org.l2j.scripts.ai.others.Spawns.NoRandomActivity,
            org.l2j.scripts.ai.others.SymbolMaker.SymbolMaker,
            org.l2j.scripts.ai.others.TeleportToRaceTrack.TeleportToRaceTrack,
            org.l2j.scripts.ai.others.TeleportWithCharm.TeleportWithCharm,
            org.l2j.scripts.ai.others.ToIVortex.ToIVortex,
            org.l2j.scripts.ai.others.WyvernManager.WyvernManager,
            org.l2j.scripts.ai.others.DivineBeast,
            org.l2j.scripts.ai.others.FairyTrees,
            org.l2j.scripts.ai.others.FleeMonsters,
            org.l2j.scripts.ai.others.Incarnation,
            org.l2j.scripts.ai.others.NonLethalableNpcs,
            org.l2j.scripts.ai.others.PolymorphingAngel,
            org.l2j.scripts.ai.others.PolymorphingOnAttack,
            org.l2j.scripts.ai.others.RandomWalkingGuards,
            org.l2j.scripts.ai.others.SeeThroughSilentMove,
            org.l2j.scripts.ai.others.SiegeGuards,
            org.l2j.scripts.ai.others.TimakOrcTroopLeader,

            org.l2j.scripts.village.master.Alliance.Alliance,
            org.l2j.scripts.village.master.Clan.Clan,
            org.l2j.scripts.village.master.DarkElfChange1.DarkElfChange1,
            org.l2j.scripts.village.master.OrcChange2.OrcChange2,
            org.l2j.scripts.village.master.OrcChange1.OrcChange1,
            org.l2j.scripts.village.master.FirstClassTransferTalk.FirstClassTransferTalk,
            org.l2j.scripts.village.master.ElfHumanWizardChange2.ElfHumanWizardChange2,
            org.l2j.scripts.village.master.ElfHumanWizardChange1.ElfHumanWizardChange1,
            org.l2j.scripts.village.master.ElfHumanFighterChange2.ElfHumanFighterChange2,
            org.l2j.scripts.village.master.ElfHumanFighterChange1.ElfHumanFighterChange1,
            org.l2j.scripts.village.master.ElfHumanClericChange2.ElfHumanClericChange2,
            org.l2j.scripts.village.master.DwarfWarehouseChange2.DwarfWarehouseChange2,
            org.l2j.scripts.village.master.DwarfWarehouseChange1.DwarfWarehouseChange1,
            org.l2j.scripts.village.master.DwarfBlacksmithChange2.DwarfBlacksmithChange2,
            org.l2j.scripts.village.master.DwarfBlacksmithChange1.DwarfBlacksmithChange1,
            org.l2j.scripts.village.master.DarkElfChange2.DarkElfChange2,

            //  custom
            org.l2j.scripts.custom.NpcLocationInfo.NpcLocationInfo;

    provides org.l2j.gameserver.handler.IActionHandler
        with ArtefactAction,
                DecoyAction,
                DoorAction,
                ItemAction,
                NpcAction,
                PlayerAction,
                PetAction,
                StaticWorldObjectAction,
                SummonAction,
                TrapAction;

    provides org.l2j.gameserver.handler.IActionShiftHandler
        with DoorActionShift,
                ItemActionShift,
                NpcActionShift,
                PlayerActionShift,
                StaticWorldObjectActionShift,
                SummonActionShift;

    provides org.l2j.gameserver.handler.IAdminCommandHandler
        with org.l2j.scripts.handlers.admincommandhandlers.AdminHtml,
            org.l2j.scripts.handlers.admincommandhandlers.AdminEditChar,
            org.l2j.scripts.handlers.admincommandhandlers.AdminShowQuests,
            org.l2j.scripts.handlers.admincommandhandlers.AdminAdmin,
            org.l2j.scripts.handlers.admincommandhandlers.AdminEnchant,
            org.l2j.scripts.handlers.admincommandhandlers.AdminMenu,
            org.l2j.scripts.handlers.admincommandhandlers.AdminPathNode,
            org.l2j.scripts.handlers.admincommandhandlers.AdminPunishment,
            org.l2j.scripts.handlers.admincommandhandlers.AdminQuest,
            org.l2j.scripts.handlers.admincommandhandlers.AdminReload,
            org.l2j.scripts.handlers.admincommandhandlers.AdminRepairChar,
            org.l2j.scripts.handlers.admincommandhandlers.AdminRes,
            org.l2j.scripts.handlers.admincommandhandlers.AdminShop,
            org.l2j.scripts.handlers.admincommandhandlers.AdminSkill,
            org.l2j.scripts.handlers.admincommandhandlers.AdminSpawn,
            org.l2j.scripts.handlers.admincommandhandlers.AdminSuperHaste,
            org.l2j.scripts.handlers.admincommandhandlers.AdminTeleport,
            org.l2j.scripts.handlers.admincommandhandlers.AdminUnblockIp,
            org.l2j.scripts.handlers.admincommandhandlers.AdminAnnouncements,
            org.l2j.scripts.handlers.admincommandhandlers.AdminBBS,
            org.l2j.scripts.handlers.admincommandhandlers.AdminBuffs,
            org.l2j.scripts.handlers.admincommandhandlers.AdminCamera,
            org.l2j.scripts.handlers.admincommandhandlers.AdminCastle,
            org.l2j.scripts.handlers.admincommandhandlers.AdminChangeAccessLevel,
            org.l2j.scripts.handlers.admincommandhandlers.AdminClan,
            org.l2j.scripts.handlers.admincommandhandlers.AdminClanHall,
            org.l2j.scripts.handlers.admincommandhandlers.AdminCreateItem,
            org.l2j.scripts.handlers.admincommandhandlers.AdminDelete,
            org.l2j.scripts.handlers.admincommandhandlers.AdminDestroyItems,
            org.l2j.scripts.handlers.admincommandhandlers.AdminDisconnect,
            org.l2j.scripts.handlers.admincommandhandlers.AdminDoorControl,
            org.l2j.scripts.handlers.admincommandhandlers.AdminEffects,
            org.l2j.scripts.handlers.admincommandhandlers.AdminEventEngine,
            org.l2j.scripts.handlers.admincommandhandlers.AdminEvents,
            org.l2j.scripts.handlers.admincommandhandlers.AdminExpSp,
            org.l2j.scripts.handlers.admincommandhandlers.AdminFence,
            org.l2j.scripts.handlers.admincommandhandlers.AdminFightCalculator,
            org.l2j.scripts.handlers.admincommandhandlers.AdminGeodata,
            org.l2j.scripts.handlers.admincommandhandlers.AdminGm,
            org.l2j.scripts.handlers.admincommandhandlers.AdminGmChat,
            org.l2j.scripts.handlers.admincommandhandlers.AdminGmSpeed,
            org.l2j.scripts.handlers.admincommandhandlers.AdminGrandBoss,
            org.l2j.scripts.handlers.admincommandhandlers.AdminHeal,
            org.l2j.scripts.handlers.admincommandhandlers.AdminHide,
            org.l2j.scripts.handlers.admincommandhandlers.AdminHwid,
            org.l2j.scripts.handlers.admincommandhandlers.AdminInstance,
            org.l2j.scripts.handlers.admincommandhandlers.AdminInstanceZone,
            org.l2j.scripts.handlers.admincommandhandlers.AdminInvul,
            org.l2j.scripts.handlers.admincommandhandlers.AdminKick,
            org.l2j.scripts.handlers.admincommandhandlers.AdminKill,
            org.l2j.scripts.handlers.admincommandhandlers.AdminLevel,
            org.l2j.scripts.handlers.admincommandhandlers.AdminLogin,
            org.l2j.scripts.handlers.admincommandhandlers.AdminManor,
            org.l2j.scripts.handlers.admincommandhandlers.AdminMessages,
            org.l2j.scripts.handlers.admincommandhandlers.AdminMissingHtmls,
            org.l2j.scripts.handlers.admincommandhandlers.AdminMobGroup,
            org.l2j.scripts.handlers.admincommandhandlers.AdminPcCafePoints,
            org.l2j.scripts.handlers.admincommandhandlers.AdminPcCondOverride,
            org.l2j.scripts.handlers.admincommandhandlers.AdminPetition,
            org.l2j.scripts.handlers.admincommandhandlers.AdminPForge,
            org.l2j.scripts.handlers.admincommandhandlers.AdminPledge,
                AdminCoins,
            org.l2j.scripts.handlers.admincommandhandlers.AdminRide,
            org.l2j.scripts.handlers.admincommandhandlers.AdminScan,
            org.l2j.scripts.handlers.admincommandhandlers.AdminServerInfo,
            org.l2j.scripts.handlers.admincommandhandlers.AdminShutdown,
            org.l2j.scripts.handlers.admincommandhandlers.AdminSummon,
            org.l2j.scripts.handlers.admincommandhandlers.AdminTarget,
            org.l2j.scripts.handlers.admincommandhandlers.AdminTargetSay,
            org.l2j.scripts.handlers.admincommandhandlers.AdminTest,
            org.l2j.scripts.handlers.admincommandhandlers.AdminTransform,
            org.l2j.scripts.handlers.admincommandhandlers.AdminVitality,
            org.l2j.scripts.handlers.admincommandhandlers.AdminZone,
            org.l2j.scripts.handlers.admincommandhandlers.AdminZones;

    provides org.l2j.gameserver.handler.IBypassHandler
        with org.l2j.scripts.handlers.bypasshandlers.NpcViewMod,
            org.l2j.scripts.handlers.bypasshandlers.Augment,
            org.l2j.scripts.handlers.bypasshandlers.Buy,
            org.l2j.scripts.handlers.bypasshandlers.ChatLink,
            org.l2j.scripts.handlers.bypasshandlers.ClanWarehouse,
            org.l2j.scripts.handlers.bypasshandlers.EnsoulWindow,
            org.l2j.scripts.handlers.bypasshandlers.EventEngine,
            org.l2j.scripts.handlers.bypasshandlers.Freight,
            org.l2j.scripts.handlers.bypasshandlers.ItemAuctionLink,
            org.l2j.scripts.handlers.bypasshandlers.Link,
            org.l2j.scripts.handlers.bypasshandlers.Multisell,
            org.l2j.scripts.handlers.bypasshandlers.Observation,
            org.l2j.scripts.handlers.bypasshandlers.OlympiadHandler,
            org.l2j.scripts.handlers.bypasshandlers.MatchHandler,
            org.l2j.scripts.handlers.bypasshandlers.PlayerHelp,
            org.l2j.scripts.handlers.bypasshandlers.PrivateWarehouse,
            org.l2j.scripts.handlers.bypasshandlers.QuestLink,
            org.l2j.scripts.handlers.bypasshandlers.SkillList,
            org.l2j.scripts.handlers.bypasshandlers.SupportBlessing,
            org.l2j.scripts.handlers.bypasshandlers.TerritoryStatus,
            org.l2j.scripts.handlers.bypasshandlers.SupportMagic,
            org.l2j.scripts.handlers.bypasshandlers.TutorialClose,
            org.l2j.scripts.handlers.bypasshandlers.UpgradeHandler,
            org.l2j.scripts.handlers.bypasshandlers.VoiceCommand,
            org.l2j.scripts.handlers.bypasshandlers.Wear,

            //custom
            org.l2j.scripts.custom.SellBuff.SellBuff;

    provides org.l2j.gameserver.handler.IChatHandler
        with org.l2j.scripts.handlers.chathandlers.ChatAlliance,
            org.l2j.scripts.handlers.chathandlers.ChatClan,
            org.l2j.scripts.handlers.chathandlers.ChatGeneral,
            org.l2j.scripts.handlers.chathandlers.ChatHeroVoice,
            org.l2j.scripts.handlers.chathandlers.ChatParty,
            org.l2j.scripts.handlers.chathandlers.ChatPartyMatchRoom,
            org.l2j.scripts.handlers.chathandlers.ChatPartyRoomAll,
            org.l2j.scripts.handlers.chathandlers.ChatPartyRoomCommander,
            org.l2j.scripts.handlers.chathandlers.ChatPetition,
            org.l2j.scripts.handlers.chathandlers.ChatShout,
            org.l2j.scripts.handlers.chathandlers.ChatTrade,
            org.l2j.scripts.handlers.chathandlers.ChatWhisper,
            org.l2j.scripts.handlers.chathandlers.ChatWorld;

    provides org.l2j.gameserver.handler.IParseBoardHandler
        with org.l2j.scripts.handlers.communityboard.FavoriteBoard,
            org.l2j.scripts.handlers.communityboard.DropSearchBoard,
            org.l2j.scripts.handlers.communityboard.ClanBoard,
            org.l2j.scripts.handlers.communityboard.RegionBoard,
            org.l2j.scripts.handlers.communityboard.FriendsBoard,
            org.l2j.scripts.handlers.communityboard.HomeBoard,
            org.l2j.scripts.handlers.communityboard.HomepageBoard,
            org.l2j.scripts.handlers.communityboard.MailBoard,
            org.l2j.scripts.handlers.communityboard.MemoBoard,

            //custom
            org.l2j.scripts.handlers.communityboard.AutoHpMpCp;

    provides org.l2j.gameserver.handler.IItemHandler
        with org.l2j.scripts.handlers.itemhandlers.ItemSkillsTemplate,
            org.l2j.scripts.handlers.itemhandlers.ItemSkills,
            org.l2j.scripts.handlers.itemhandlers.BeastSoulShot,
            org.l2j.scripts.handlers.itemhandlers.BeastSpiritShot,
            org.l2j.scripts.handlers.itemhandlers.BlessedBeastSpiritShot,
            org.l2j.scripts.handlers.itemhandlers.BlessedSoulShots,
            org.l2j.scripts.handlers.itemhandlers.BlessedSpiritShot,
            org.l2j.scripts.handlers.itemhandlers.Book,
            org.l2j.scripts.handlers.itemhandlers.Bypass,
            org.l2j.scripts.handlers.itemhandlers.Calculator,
            org.l2j.scripts.handlers.itemhandlers.CharmOfCourage,
            org.l2j.scripts.handlers.itemhandlers.Elixir,
            org.l2j.scripts.handlers.itemhandlers.EnchantScrolls,
            org.l2j.scripts.handlers.itemhandlers.EventItem,
            org.l2j.scripts.handlers.itemhandlers.ExtractableItems,
            org.l2j.scripts.handlers.itemhandlers.FatedSupportBox,
            org.l2j.scripts.handlers.itemhandlers.FishShots,
            org.l2j.scripts.handlers.itemhandlers.Harvester,
            org.l2j.scripts.handlers.itemhandlers.Maps,
            org.l2j.scripts.handlers.itemhandlers.MercTicket,
            org.l2j.scripts.handlers.itemhandlers.NicknameColor,
            org.l2j.scripts.handlers.itemhandlers.PetFood,
            org.l2j.scripts.handlers.itemhandlers.Recipes,
            org.l2j.scripts.handlers.itemhandlers.RollingDice,
            org.l2j.scripts.handlers.itemhandlers.Seed,
            org.l2j.scripts.handlers.itemhandlers.SoulShots,
            org.l2j.scripts.handlers.itemhandlers.SpecialXMas,
            org.l2j.scripts.handlers.itemhandlers.SpiritShot,
            org.l2j.scripts.handlers.itemhandlers.SummonItems,
                TransformationBook,
                org.l2j.scripts.handlers.itemhandlers.BlessedScroll;

    provides org.l2j.gameserver.handler.IPunishmentHandler
        with org.l2j.scripts.handlers.punishmenthandlers.BanHandler,
            org.l2j.scripts.handlers.punishmenthandlers.ChatBanHandler,
            org.l2j.scripts.handlers.punishmenthandlers.JailHandler;

    provides org.l2j.gameserver.handler.IUserCommandHandler
        with org.l2j.scripts.handlers.usercommandhandlers.ClanWarsList,
            org.l2j.scripts.handlers.usercommandhandlers.ChannelDelete,
            org.l2j.scripts.handlers.usercommandhandlers.ChannelInfo,
            org.l2j.scripts.handlers.usercommandhandlers.ChannelLeave,
            org.l2j.scripts.handlers.usercommandhandlers.ClanPenalty,
            org.l2j.scripts.handlers.usercommandhandlers.Dismount,
            org.l2j.scripts.handlers.usercommandhandlers.Unstuck,
            org.l2j.scripts.handlers.usercommandhandlers.Time,
            org.l2j.scripts.handlers.usercommandhandlers.SiegeStatus,
            org.l2j.scripts.handlers.usercommandhandlers.PartyInfo,
            org.l2j.scripts.handlers.usercommandhandlers.OlympiadStat,
            org.l2j.scripts.handlers.usercommandhandlers.MyBirthday,
            org.l2j.scripts.handlers.usercommandhandlers.Mount,
            org.l2j.scripts.handlers.usercommandhandlers.Loc,
            org.l2j.scripts.handlers.usercommandhandlers.InstanceZone;

    provides org.l2j.gameserver.handler.IVoicedCommandHandler
        with org.l2j.scripts.handlers.voicedcommandhandlers.ExperienceGain,
            org.l2j.scripts.handlers.voicedcommandhandlers.SetVCmd,
            org.l2j.scripts.handlers.voicedcommandhandlers.CastleVCmd,
            org.l2j.scripts.handlers.voicedcommandhandlers.Lang,
            org.l2j.scripts.handlers.voicedcommandhandlers.ChatAdmin,
            org.l2j.scripts.handlers.voicedcommandhandlers.Banking,
            org.l2j.scripts.handlers.voicedcommandhandlers.ChangePassword,
            org.l2j.scripts.handlers.voicedcommandhandlers.AutoPotion,
            org.l2j.scripts.handlers.voicedcommandhandlers.Donate,

            //custom
            org.l2j.scripts.custom.SellBuff.SellBuff;


    provides org.l2j.gameserver.handler.ITargetTypeHandler
        with org.l2j.scripts.handlers.targethandlers.WyvernTarget,
            org.l2j.scripts.handlers.targethandlers.Target,
            org.l2j.scripts.handlers.targethandlers.Summon,
            org.l2j.scripts.handlers.targethandlers.Self,
            org.l2j.scripts.handlers.targethandlers.PcBody,
            org.l2j.scripts.handlers.targethandlers.OwnerPet,
            org.l2j.scripts.handlers.targethandlers.Others,
            org.l2j.scripts.handlers.targethandlers.NpcBody,
            org.l2j.scripts.handlers.targethandlers.None,
            org.l2j.scripts.handlers.targethandlers.MyParty,
            org.l2j.scripts.handlers.targethandlers.Item,
            org.l2j.scripts.handlers.targethandlers.HolyThing,
            org.l2j.scripts.handlers.targethandlers.Ground,
            org.l2j.scripts.handlers.targethandlers.FortressFlagpole,
            org.l2j.scripts.handlers.targethandlers.Enemy,
            org.l2j.scripts.handlers.targethandlers.EnemyOnly,
            org.l2j.scripts.handlers.targethandlers.EnemyNot,
            org.l2j.scripts.handlers.targethandlers.DoorTreasure,
            org.l2j.scripts.handlers.targethandlers.AdvanceBase,
            org.l2j.scripts.handlers.targethandlers.Artillery;

    provides org.l2j.gameserver.handler.IAffectObjectHandler
        with org.l2j.scripts.handlers.targethandlers.affectobject.All,
            org.l2j.scripts.handlers.targethandlers.affectobject.WyvernObject,
            org.l2j.scripts.handlers.targethandlers.affectobject.UndeadRealEnemy,
            org.l2j.scripts.handlers.targethandlers.affectobject.ObjectDeadNpcBody,
            org.l2j.scripts.handlers.targethandlers.affectobject.NotFriend,
            org.l2j.scripts.handlers.targethandlers.affectobject.NotFriendPc,
            org.l2j.scripts.handlers.targethandlers.affectobject.Invisible,
            org.l2j.scripts.handlers.targethandlers.affectobject.HiddenPlace,
            org.l2j.scripts.handlers.targethandlers.affectobject.Friend,
            org.l2j.scripts.handlers.targethandlers.affectobject.FriendPc,
            org.l2j.scripts.handlers.targethandlers.affectobject.Clan;

    provides org.l2j.gameserver.handler.IAffectScopeHandler
        with org.l2j.scripts.handlers.targethandlers.affectscope.BalakasScope,
            org.l2j.scripts.handlers.targethandlers.affectscope.WyvernScope,
            org.l2j.scripts.handlers.targethandlers.affectscope.SummonExceptMaster,
            org.l2j.scripts.handlers.targethandlers.affectscope.StaticObjectScope,
            org.l2j.scripts.handlers.targethandlers.affectscope.SquarePB,
            org.l2j.scripts.handlers.targethandlers.affectscope.Single,
            org.l2j.scripts.handlers.targethandlers.affectscope.RingRange,
            org.l2j.scripts.handlers.targethandlers.affectscope.RangeSortByHp,
            org.l2j.scripts.handlers.targethandlers.affectscope.PointBlank,
            org.l2j.scripts.handlers.targethandlers.affectscope.Pledge,
            org.l2j.scripts.handlers.targethandlers.affectscope.PartyPledge,
            org.l2j.scripts.handlers.targethandlers.affectscope.FanPB,
            org.l2j.scripts.handlers.targethandlers.affectscope.DeadUnion,
            org.l2j.scripts.handlers.targethandlers.affectscope.DeadPledge,
            org.l2j.scripts.handlers.targethandlers.affectscope.DeadParty,
            org.l2j.scripts.handlers.targethandlers.affectscope.Square,
            org.l2j.scripts.handlers.targethandlers.affectscope.Fan,
            org.l2j.scripts.handlers.targethandlers.affectscope.Party,
            org.l2j.scripts.handlers.targethandlers.affectscope.Range,
            org.l2j.scripts.handlers.targethandlers.affectscope.DeadPartyPledge;

    provides org.l2j.gameserver.handler.IPlayerActionHandler
        with org.l2j.scripts.handlers.playeractions.ActionHandler,
            org.l2j.scripts.handlers.playeractions.PrivateStore,
            org.l2j.scripts.handlers.playeractions.UnsummonServitor,
            org.l2j.scripts.handlers.playeractions.UnsummonPet,
            org.l2j.scripts.handlers.playeractions.TeleportBookmark,
            org.l2j.scripts.handlers.playeractions.TacticalSignUse,
            org.l2j.scripts.handlers.playeractions.TacticalSignTarget,
            org.l2j.scripts.handlers.playeractions.SocialAction,
            org.l2j.scripts.handlers.playeractions.SitStand,
            org.l2j.scripts.handlers.playeractions.ServitorStop,
            org.l2j.scripts.handlers.playeractions.ServitorSkillUse,
            org.l2j.scripts.handlers.playeractions.ServitorMove,
            org.l2j.scripts.handlers.playeractions.ServitorMode,
            org.l2j.scripts.handlers.playeractions.ServitorHold,
            org.l2j.scripts.handlers.playeractions.ServitorAttack,
            org.l2j.scripts.handlers.playeractions.RunWalk,
            org.l2j.scripts.handlers.playeractions.Ride,
            org.l2j.scripts.handlers.playeractions.PetStop,
            org.l2j.scripts.handlers.playeractions.PetSkillUse,
            org.l2j.scripts.handlers.playeractions.PetMove,
            org.l2j.scripts.handlers.playeractions.PetHold,
            org.l2j.scripts.handlers.playeractions.PetAttack,
            org.l2j.scripts.handlers.playeractions.InstanceZoneInfo,
            org.l2j.scripts.handlers.playeractions.BotReport;

    provides org.l2j.gameserver.model.quest.Quest
        with
             org.l2j.scripts.quests.Q00127_FishingSpecialistsRequest.Q00127_FishingSpecialistsRequest,
                Q10960_Tutorial,
                Q201_Tutorial,
                Q202_Tutorial,
                Q203_Tutorial,
                Q204_Tutorial,
                Q205_Tutorial,
                Q206_Tutorial,
             org.l2j.scripts.quests.Q00300_HuntingLetoLizardman.Q00300_HuntingLetoLizardman,
             org.l2j.scripts.quests.Q00326_VanquishRemnants.Q00326_VanquishRemnants,
             org.l2j.scripts.quests.Q00327_RecoverTheFarmland.Q00327_RecoverTheFarmland,
             org.l2j.scripts.quests.Q00328_SenseForBusiness.Q00328_SenseForBusiness,
             org.l2j.scripts.quests.Q00329_CuriosityOfADwarf.Q00329_CuriosityOfADwarf,
             org.l2j.scripts.quests.Q00331_ArrowOfVengeance.Q00331_ArrowOfVengeance,
             org.l2j.scripts.quests.Q00333_HuntOfTheBlackLion.Q00333_HuntOfTheBlackLion,
             org.l2j.scripts.quests.Q00344_1000YearsTheEndOfLamentation.Q00344_1000YearsTheEndOfLamentation,
             org.l2j.scripts.quests.Q00354_ConquestOfAlligatorIsland.Q00354_ConquestOfAlligatorIsland,
             org.l2j.scripts.quests.Q00355_FamilyHonor.Q00355_FamilyHonor,
             org.l2j.scripts.quests.Q00356_DigUpTheSeaOfSpores.Q00356_DigUpTheSeaOfSpores,
             org.l2j.scripts.quests.Q00358_IllegitimateChildOfTheGoddess.Q00358_IllegitimateChildOfTheGoddess,
             org.l2j.scripts.quests.Q00360_PlunderTheirSupplies.Q00360_PlunderTheirSupplies,
             org.l2j.scripts.quests.Q00369_CollectorOfJewels.Q00369_CollectorOfJewels,
             org.l2j.scripts.quests.Q00370_AnElderSowsSeeds.Q00370_AnElderSowsSeeds,
             org.l2j.scripts.quests.Q00500_BrothersBoundInChains.Q00500_BrothersBoundInChains,
             org.l2j.scripts.quests.Q00662_AGameOfCards.Q00662_AGameOfCards,
             org.l2j.scripts.quests.Q00933_ExploringTheWestWingOfTheDungeonOfAbyss.Q00933_ExploringTheWestWingOfTheDungeonOfAbyss,
             org.l2j.scripts.quests.Q00935_ExploringTheEastWingOfTheDungeonOfAbyss.Q00935_ExploringTheEastWingOfTheDungeonOfAbyss,
             org.l2j.scripts.quests.Q10866_PunitiveOperationOnTheDevilIsle.Q10866_PunitiveOperationOnTheDevilIsle,
             org.l2j.scripts.quests.Q10961_EffectiveTraining.Q10961_EffectiveTraining,
             org.l2j.scripts.quests.Q10962_NewHorizons.Q10962_NewHorizons,
             org.l2j.scripts.quests.Q10963_ExploringTheAntNest.Q10963_ExploringTheAntNest,
             org.l2j.scripts.quests.Q10964_SecretGarden.Q10964_SecretGarden,
             org.l2j.scripts.quests.Q10965_DeathMysteries.Q10965_DeathMysteries,
             org.l2j.scripts.quests.Q10966_ATripBegins.Q10966_ATripBegins,
             org.l2j.scripts.quests.Q10967_CulturedAdventurer.Q10967_CulturedAdventurer,
             org.l2j.scripts.quests.Q10981_UnbearableWolvesHowling.Q10981_UnbearableWolvesHowling,
             org.l2j.scripts.quests.Q10982_SpiderHunt.Q10982_SpiderHunt,
             org.l2j.scripts.quests.Q10983_TroubledForest.Q10983_TroubledForest,
             org.l2j.scripts.quests.Q10984_CollectSpiderweb.Q10984_CollectSpiderweb,
             org.l2j.scripts.quests.Q10985_CleaningUpTheGround.Q10985_CleaningUpTheGround,
             org.l2j.scripts.quests.Q10986_SwampMonster.Q10986_SwampMonster,
             org.l2j.scripts.quests.Q10987_PlunderedGraves.Q10987_PlunderedGraves,
             org.l2j.scripts.quests.Q10988_Conspiracy.Q10988_Conspiracy,
             org.l2j.scripts.quests.Q10989_DangerousPredators.Q10989_DangerousPredators,
             org.l2j.scripts.quests.Q10990_PoisonExtraction.Q10990_PoisonExtraction,
             org.l2j.scripts.quests.Q00620_FourGoblets.Q00620_FourGoblets,
             org.l2j.scripts.quests.Q00630_PirateTreasureHunt.Q00630_PirateTreasureHunt,
             org.l2j.scripts.quests.Q10871_DeathToThePirateKing.Q10871_DeathToThePirateKing;


    provides org.l2j.gameserver.engine.mission.MissionHandlerFactory
        with org.l2j.scripts.handlers.mission.LevelMissionHandler.Factory,
            org.l2j.scripts.handlers.mission.BossMissionHandler.Factory,
            org.l2j.scripts.handlers.mission.ClanMissionHandler.Factory,
            org.l2j.scripts.handlers.mission.FishingMissionHandler.Factory,
            org.l2j.scripts.handlers.mission.HuntMissionHandler.Factory,
            org.l2j.scripts.handlers.mission.LoginMissionHandler.Factory,
            org.l2j.scripts.handlers.mission.OlympiadMissionHandler.Factory,
            org.l2j.scripts.handlers.mission.QuestMissionHandler.Factory,
            org.l2j.scripts.handlers.mission.SiegeMissionHandler.Factory,
            org.l2j.scripts.handlers.mission.SpiritMissionHandler.Factory;

}
