DROP TABLE IF EXISTS `crests`;
CREATE TABLE IF NOT EXISTS `crests` (
	`id` INT NOT NULL ,
	`data` VARBINARY(2176) NOT NULL,
	`type` ENUM('PLEDGE' , 'PLEDGE_LARGE', 'ALLY') NOT NULL ,
	PRIMARY KEY(`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8MB4;