DROP TABLE IF EXISTS boss_data;
CREATE TABLE IF NOT EXISTS boss_data (
  `boss_id` INT NOT NULL,
  `x` INT NOT NULL,
  `y` INT NOT NULL,
  `z` INT NOT NULL,
  `heading` MEDIUMINT NOT NULL DEFAULT 0,
  `respawn_time` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `hp` DOUBLE NOT NULL,
  `mp` DOUBLE NOT NULL,
  PRIMARY KEY (`boss_id`)
)  ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;