DROP TABLE IF EXISTS `player_variables`;
CREATE TABLE IF NOT EXISTS `player_variables` (
    `player_id` INT UNSIGNED NOT NULL,
    `revenge_teleports` SMALLINT NOT NULL DEFAULT 0,
    `revenge_locations` SMALLINT NOT NULL DEFAULT 0,
    `hair_accessory_enabled` BOOLEAN DEFAULT TRUE,
    `world_chat_used` INT DEFAULT 0,
	`vitality_items_used` INT DEFAULT 0,
	`ability_points_main_class_used` INT DEFAULT 0,
	`revelation_skill_main_class_1` INT DEFAULT 0,
	`revelation_skill_main_class_2` INT DEFAULT 0,
	`extend_drop` VARCHAR(255),
	`fortune_telling` INT DEFAULT 0,
	`fortune_telling_black_cat` BOOLEAN DEFAULT FALSE,
	`hunting_zone_reset_time` VARCHAR(255),
	`autocp` INT DEFAULT 0,
	`autohp` INT DEFAULT 0,
	`automp` INT DEFAULT 0,
	`exp_off` BOOLEAN DEFAULT FALSE,
	`items_rewarded` BOOLEAN DEFAULT FALSE,
	`henna1_duration` BIGINT DEFAULT 0,
	`henna2_duration` BIGINT DEFAULT 0,
	`henna3_duration` BIGINT DEFAULT 0,
	`visual_hair_id` INT,
	`visual_hair_color_id` INT,
	`visual_face_id` INT,
	`instance_restore` INT DEFAULT 0,
	`claimed_clan_rewards` INT DEFAULT 0,
	`cond_override_key` VARCHAR(255),
	`ui_key_mapping` VARCHAR(255),
	`monster_return` INT DEFAULT -1,
	`lamp_xp` INT DEFAULT 0,
	`lamp_count` INT DEFAULT 0,
	`soulshot` INT DEFAULT 0,
	`spiritshot` INT DEFAULT 0,
    PRIMARY KEY (`player_id`),
    FOREIGN KEY (`player_id`) REFERENCES characters(`charId`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

