DROP TABLE IF EXISTS `punishments`;
CREATE TABLE IF NOT EXISTS `punishments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `key` varchar(255) NOT NULL,
  `affect` ENUM('ACCOUNT', 'CHARACTER', 'IP') NOT NULL,
  `type` ENUM('JAIL', 'BAN', 'PERMANENT_BAN', 'CHAT_BAN', 'PARTY_BAN') NOT NULL,
  `expiration`  BIGINT NOT NULL,
  `reason` TEXT NOT NULL,
  `punisher` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
)  ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;